version: "3.8"
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: my_bank

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=root:root@tcp(mysql:3306)/my_bank?charset=utf8mb4&parseTime=True&loc=Local
  
