services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_bank
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - my_network


  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=mysql
      - DB_SOURCE=root:root@tcp(mysql:3306)/simple_bank?charset=utf8mb4&parseTime=True&loc=Local&multiStatements=true
      - ADDRESS_SERVER=0.0.0.0:8080
      - ACCESS_TOKEN_DURATION=15m
      - SECRET_KEY=AgdsFwUdpy163md78aohge6FHsi839F2
    depends_on:
       mysql:
        condition: service_healthy
    entrypoint: ["/app/start.sh"]
    command: ["/app/main"]
    networks:
      - my_network


networks:
  my_network:


