// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routes

import (
	"github.com/google/wire"
	"simple_bank_solid/api/controller"
	"simple_bank_solid/api/repository"
	"simple_bank_solid/api/service"
)

// Injectors from injector.go:

func InitializSessionController() controller.SessionController {
	sessionRepository := repository.NewSessionRepository()
	sessionService := service.NewSessionService(sessionRepository)
	sessionController := controller.NewSessionController(sessionService)
	return sessionController
}

func InitializeUserController() controller.UserController {
	accountRepository := repository.NewAccountRepository()
	userRepository := repository.NewUserRepository()
	sessionRepository := repository.NewSessionRepository()
	userService := service.NewUserService(accountRepository, userRepository, sessionRepository)
	userController := controller.NewUserController(userService)
	return userController
}

func InitializeAccountController() controller.AccountController {
	accountRepository := repository.NewAccountRepository()
	accountService := service.NewAccountService(accountRepository)
	accountController := controller.NewAccountController(accountService)
	return accountController
}

func InitializeDepositController() controller.DepositController {
	accountRepository := repository.NewAccountRepository()
	depositRepository := repository.NewDepositRepository()
	entriesRepository := repository.NewEntriesRepository()
	depositServie := service.NewDepositService(accountRepository, depositRepository, entriesRepository)
	depositController := controller.NewDepositController(depositServie)
	return depositController
}

func InitializeTransactionController() controller.TransactionController {
	accountRepository := repository.NewAccountRepository()
	transactionRepository := repository.NewTransactionRepository()
	entriesRepository := repository.NewEntriesRepository()
	transactionService := service.NewTransactionService(accountRepository, transactionRepository, entriesRepository)
	transactionController := controller.NewTransactionController(transactionService)
	return transactionController
}

// injector.go:

var SessionSet = wire.NewSet(repository.NewSessionRepository, service.NewSessionService, controller.NewSessionController)

var UserSet = wire.NewSet(repository.NewUserRepository, repository.NewAccountRepository, repository.NewSessionRepository, service.NewUserService, controller.NewUserController)

var AccountSet = wire.NewSet(repository.NewAccountRepository, service.NewAccountService, controller.NewAccountController)

var DepositSet = wire.NewSet(repository.NewAccountRepository, repository.NewDepositRepository, repository.NewEntriesRepository, service.NewDepositService, controller.NewDepositController)

var TransactionSet = wire.NewSet(repository.NewAccountRepository, repository.NewTransactionRepository, repository.NewEntriesRepository, service.NewTransactionService, controller.NewTransactionController)
